### 범주형 자료의 실수화
: 원핫 인코딩

In [1]:
# 범주형 자료형
x=[{'city':'seoul','temp':10.0},{'city':'Dubai','temp':23.0},{'city':'LA','temp':20.0}]
x

[{'city': 'seoul', 'temp': 10.0},
 {'city': 'Dubai', 'temp': 23.0},
 {'city': 'LA', 'temp': 20.0}]

In [3]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer(sparse=False) # sparse=True 는 불필요한거 없애서 데이터 확보
vec.fit_transform(x)

array([[ 0.,  0.,  1., 10.],
       [ 1.,  0.,  0., 23.],
       [ 0.,  1.,  0., 20.]])

### 텍스트 자료의 실수화

In [6]:
text =['떴다 떴다 비행기 날아라 날아라',
       '높이 높이 날아라 우리 비행기',
       '내가 만든 비행기 날아라 날아라',
       '멀리 멀리 날아라 우리 비핼기']

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
vec2 = CountVectorizer() # 디폴트값이 sparse=True 
t = vec2.fit_transform(text).toarray() # sparse=false로 하고 text를 수 배열로 변환
import pandas as pd
t1 = pd.DataFrame(t,columns = vec2.get_feature_names()) # 각 열의 항목에 이름들을 가져온다
t1

   날아라  내가  높이  떴다  만든  멀리  비핼기  비행기  우리
0    2   0   0   2   0   0    0    1   0
1    1   0   2   0   0   0    0    1   1
2    2   1   0   0   1   0    0    1   0
3    1   0   0   0   0   2    1    0   1

#### tf-idf
: 의미 없는 단어의 가중치를 줄이고자 비중많은 것은 가중치 줄이고 적은것은 높임

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()
x2 = tfid.fit_transform(text).toarray()
x3 = pd.DataFrame(x2,columns = tfid.get_feature_names())
x3

        날아라        내가        높이  ...       비핼기       비행기        우리
0  0.445162  0.000000  0.000000  ...  0.000000  0.272249  0.000000
1  0.226645  0.000000  0.868636  ...  0.000000  0.277220  0.342421
2  0.558136  0.534776  0.000000  ...  0.000000  0.341340  0.000000
3  0.214950  0.000000  0.000000  ...  0.411906  0.000000  0.324751

[4 rows x 9 columns]